### PR TITLE
shorten down volume options

### PR DESCRIPTION
**Pull request by lzlrd**
we seem to now have a LOT of volume options i thought we should shorten it down

fixedd a few missing lines that were in the wrong places too :P

### CODE REVIEW

**Comment by lzlrd** [comment]
~~i'd need someone to update README.md and increment if this is to follow through~~ done

oh and PS - @JohnFawkes seems like the bootanimation was getting installed anyways as it's still in $INSTALLER/system/media

**Comment by lzlrd** [comment]
@JohnFawkes of u could include a afix for the htc bootanimation problem u mentioned earlier i'd be grateful

**Comment by lzlrd** [comment]
and there's also a test zip here https://github.com/lazerl0rd/Pix3lify/releases

**Comment by thehappydinoa** [comment]
Hey, you removed the boot animation and most options for the user...

**Comment by JohnFawkes** [comment]
personally i dont think there was too many options. i think what we had was perfectly fine. ill look into why the boot animation is still getting installed even choosing no and im working on xmlstarlet

**Comment by ThatNerdyPikachu** [comment]
The boot animation was not being Installed for me if I pressed no..

**Comment by JohnFawkes** [comment]
> The boot animation was not being Installed for me if I pressed no..

maybe he was talking about with his changes?

**Comment by thehappydinoa** [comment]
> The boot animation was not being Installed for me if I pressed no..

I fixed this in 38bb090

> personally i dont think there was too many options. i think what we had was perfectly fine. ill look into why the boot animation is still getting installed even choosing no and im working on xmlstarlet

I agree with this, I think we should give users more options rather than less so each person can pick exactly how much they want to be installed.

**Review by thehappydinoa — CHANGES_REQUESTED** [review]
You deleted the bootanimation which is used by the `install.sh` script not the one installed in `/system/media/`. Please add this back as different phones have differnt paths.

**Review by joeyhuab — CHANGES_REQUESTED** [review]
Personally, ever since way back as the Pixel Experience module with the launcher choices, I always wanted to give users more options to futher personalize their experience with the module similar to what V4A and JDSP have done. I always wanted to provide users with a similar experience but I didn't really have a good grasp on the codes within Magisk and Unity which effectively crippled my efforts until you guys showed up which I really dig most changes that have been added up to this point. With all that said, we should provide the end user with more options to futher give them control of the module.

**Comment by lzlrd** [comment]
Alright, let's keep options how it was then :).

**Pull request closed without merging**
