### PR TITLE
Disable Flip to Shh

### PR DESCRIPTION
**Pull request by ThatNerdyPikachu**
That should be everything!

### CODE REVIEW

**Comment by ThatNerdyPikachu** [comment]
paging @Stallix, is the latest commit (https://github.com/Magisk-Modules-Repo/Pix3lify/pull/17/commits/69d2909f105e0192c43a6317aecbb9104878180d) a good change?

**Comment by joeyhuab** [comment]
Both correct. TY

**Comment by ThatNerdyPikachu** [comment]
i guess that was a yes

**Comment by joeyhuab** [comment]
Sent u a collab invite for the module

**Comment by ThatNerdyPikachu** [comment]
thanks, should we bump version?

**Comment by joeyhuab** [comment]
Yes please. Feel free to do it.

**Comment by ThatNerdyPikachu** [comment]
Done!

**Comment by ThatNerdyPikachu** [comment]
@Stallix Can you make sure everything works? Can't test atm.

**Pull request merged**
